services:

    front-service-dependencies:
        image: node:22.15.0-alpine3.21
        container_name: front-service-dependencies
        working_dir: /app
        volumes:
            - ./:/app
        command: npm install

    front-service-dev:
        image: node:22.15.0-alpine3.21
        container_name: front-service-dev
        working_dir: /app
        volumes:
            - ./:/app
        ports:
            - 3000:3000
        depends_on:
            front-service-dependencies:
                condition: service_completed_successfully
        command: sh -c "npm run test && npm dev"
        environment:
        - API_KEY=5a2f939e2bd7ea0f72adce5ff1c714f2
        - API_BASE=http://api.openweathermap.org


    front-service-build:
        image: node:22.15.0-alpine3.21
        container_name: front-service-build
        working_dir: /app
        volumes:
            - ./:/app
        depends_on:
            front-service-dependencies:
                condition: service_completed_successfully
        command: npm run build

    front-service-prod:
        image: node:22.15.0-alpine3.21
        container_name: front-service-prod
        working_dir: /app
        volumes:
            - ./:/app
        ports:
            - 3000:3000
        depends_on:
            front-service-build:
                condition: service_completed_successfully
        command: sh -c "npm run test && npm start"
        environment:
        - API_KEY=5a2f939e2bd7ea0f72adce5ff1c714f2
        - API_BASE=http://api.openweathermap.org